services:
    app:
        build:
            context: .
            target: production
        restart: unless-stopped
        env_file:
            - .env
        volumes:
            - ./database:/app/database
        command: npm start
        networks:
            - weather

networks:
    weather:
        name: weather
