/**
 * SQLite Database Driver Helper.
 * Adapted from the node-aec database driver architecture for Node.js 26 native node:sqlite.
 * 
 * Provides a structured, query-builder and CRUD-oriented database access layer.
 * 
 * @module database/driver
 */

import { DatabaseSync } from 'node:sqlite';
import { resolve } from 'node:path';

/**
 * Custom Error class for database operations.
 */
export class DatabaseError extends Error {
    /**
     * @param {number} statusCode
     * @param {string} message
     * @param {string} [code]
     * @param {unknown} [data]
     */
    constructor(statusCode, message, code = 'DATABASE_ERROR', data = null) {
        super(message);
        this.name = 'DatabaseError';
        this.statusCode = statusCode;
        this.code = code;
        this.data = data;
    }
}

/**
 * Shared SQLite database driver helper.
 */
export class Sqlite {
    static connected = false;
    static connection = null;
    static #rawSqlSentinel = Symbol('raw-sql-fragment');

    static get config() {
        return {
            path: process.env.SQLITE_DB_PATH || process.env.DB_PATH || 'weather_logs.db'
        };
    }

    /**
     * Opens the shared SQLite database connection when needed.
     *
     * @param {{ path?: string }} [config]
     * @returns {typeof Sqlite}
     */
    static connect(config = {}) {
        if (Sqlite.connected && Sqlite.connection) {
            return this;
        }

        const dbPath = config.path || Sqlite.config.path;
        if (dbPath === ':memory:') {
            Sqlite.connection = new DatabaseSync(':memory:');
        } else {
            const resolved = resolve(dbPath);
            Sqlite.connection = new DatabaseSync(resolved);
            try {
                Sqlite.connection.exec('PRAGMA journal_mode = WAL;');
                Sqlite.connection.exec('PRAGMA synchronous = NORMAL;');
            } catch {
                // WAL mode may not apply in all environments
            }
        }

        Sqlite.connected = true;
        return this;
    }

    /**
     * Closes the active database connection.
     *
     * @returns {typeof Sqlite}
     */
    static close() {
        if (!Sqlite.connected || !Sqlite.connection) {
            return this;
        }
        try {
            Sqlite.connection.close();
        } catch {
            // Ignore close errors
        }
        Sqlite.connection = null;
        Sqlite.connected = false;
        return this;
    }

    /**
     * Verifies that SQLite can answer a constant query.
     *
     * @returns {Promise<boolean>|boolean}
     */
    static ping() {
        Sqlite.#query('SELECT 1');
        return true;
    }

    /**
     * Executes arbitrary DDL/SQL statements (like CREATE TABLE).
     *
     * @param {string} sql
     * @param {{ connection?: DatabaseSync }} [context]
     * @returns {void}
     */
    static exec(sql, { connection } = {}) {
        if (!connection && !Sqlite.connected) {
            Sqlite.connect();
        }
        const executor = connection || Sqlite.connection;
        executor.exec(sql);
    }

    /**
     * Quotes SQL identifiers using double quotes, handling dotted table or column references.
     *
     * @param {string} identifier
     * @returns {string}
     */
    static #quoteIdentifier(identifier) {
        return String(identifier)
            .split('.')
            .map(part => {
                if (part === '*') return '*';
                return `"${part.replace(/"/g, '""')}"`;
            })
            .join('.');
    }

    /**
     * Validates and sanitizes write payloads by dropping undefined fields.
     *
     * @param {Record<string, unknown>} data
     * @param {string} operation
     * @returns {Record<string, unknown>}
     */
    static #sanitizeWriteData(data, operation) {
        if (!data || typeof data !== 'object' || Array.isArray(data)) {
            throw new DatabaseError(400, `Invalid data for ${operation} operation.`);
        }

        const sanitized = Object.fromEntries(
            Object.entries(data).filter(([, value]) => value !== undefined)
        );

        if (!Object.keys(sanitized).length) {
            throw new DatabaseError(400, `No data to ${operation}.`);
        }

        return sanitized;
    }

    /**
     * Executes parameterized SQL generated by this helper.
     *
     * @param {string} sql
     * @param {unknown[]} [data]
     * @param {{ connection?: DatabaseSync }} [context]
     * @returns {unknown[]}
     */
    static #query(sql, data = [], { connection } = {}) {
        if (!connection && !Sqlite.connected) {
            Sqlite.connect();
        }

        const executor = connection || Sqlite.connection;
        const raw = Sqlite.formatRaw(sql, data);
        const cleanSql = raw.sql.trim();

        try {
            const stmt = executor.prepare(cleanSql);
            if (cleanSql.toUpperCase().startsWith('SELECT') || cleanSql.toUpperCase().includes('RETURNING')) {
                const rows = stmt.all(...raw.data);
                return (rows || []).map(row => {
                    if (row && typeof row === 'object' && !('insertId' in row) && 'id' in row) {
                        Object.defineProperty(row, 'insertId', {
                            get() {
                                return this.id;
                            },
                            enumerable: false,
                            configurable: true,
                        });
                    }
                    return row;
                });
            } else {
                const result = stmt.run(...raw.data);
                return [{
                    insertId: Number(result.lastInsertRowid),
                    changes: Number(result.changes)
                }];
            }
        } catch (error) {
            throw new DatabaseError(500, error.message, 'SQL_EXECUTION_ERROR', error);
        }
    }

    /**
     * Inserts one or more rows into a table.
     *
     * @param {string} table
     * @param {Record<string, unknown>|Record<string, unknown>[]} data
     * @param {{ connection?: DatabaseSync }} [context]
     * @returns {unknown[]}
     */
    static insert(table, data, context = {}) {
        if (!data) {
            throw new DatabaseError(400, 'Invalid data for insert operation.');
        }
        const rows = Array.isArray(data) ? data : [data];

        return rows.map(row => {
            const sanitizedRow = Sqlite.#sanitizeWriteData(row, 'insert');
            const fields = Object.keys(sanitizedRow);
            const values = Object.values(sanitizedRow);
            const fieldSql = fields.map(field => Sqlite.#quoteIdentifier(field)).join(',');
            const valueSql = fields.map(() => '?').join(',');
            const sql = `INSERT INTO ${Sqlite.#quoteIdentifier(table)} (${fieldSql}) VALUES (${valueSql}) RETURNING *`;
            const result = Sqlite.#query(sql, values, context);
            return result[0];
        });
    }

    /**
     * Inserts a row and updates selected fields on conflict.
     *
     * @param {string} table
     * @param {Record<string, unknown>} data
     * @param {{ conflictFields?: string[], updateFields?: string[] }} [options]
     * @param {{ connection?: DatabaseSync }} [context]
     * @returns {unknown[]}
     */
    static upsert(table, data, { conflictFields = [], updateFields = [] } = {}, context = {}) {
        const sanitizedData = Sqlite.#sanitizeWriteData(data, 'upsert');
        const fields = Object.keys(sanitizedData);
        const updatableFields = (updateFields.length ? updateFields : fields)
            .filter(field => !conflictFields.includes(field));

        if (!updatableFields.length) {
            throw new DatabaseError(400, 'No update fields provided for upsert operation.');
        }

        const conflictTarget = conflictFields.length
            ? conflictFields.map(f => Sqlite.#quoteIdentifier(f)).join(', ')
            : Sqlite.#quoteIdentifier('id');

        const fieldSql = fields.map(field => Sqlite.#quoteIdentifier(field)).join(',');
        const valueSql = fields.map(() => '?').join(',');
        const updateSql = updatableFields
            .map(field => `${Sqlite.#quoteIdentifier(field)} = excluded.${Sqlite.#quoteIdentifier(field)}`)
            .join(', ');
        const sql = `INSERT INTO ${Sqlite.#quoteIdentifier(table)} (${fieldSql}) VALUES (${valueSql}) ON CONFLICT (${conflictTarget}) DO UPDATE SET ${updateSql} RETURNING *`;

        return Sqlite.#query(sql, fields.map(field => sanitizedData[field]), context);
    }

    /**
     * Updates rows by id or by a filter object.
     *
     * @param {string} table
     * @param {Record<string, unknown>} data
     * @param {number|string|Record<string, unknown>} id
     * @param {{ connection?: DatabaseSync }} [context]
     * @returns {unknown[]}
     */
    static update(table, data, id, context = {}) {
        if (id === undefined || id === null) {
            throw new DatabaseError(400, 'No identifier provided for update.');
        }

        data = Sqlite.#sanitizeWriteData(data, 'update');

        const values = Object.values(data);
        const fieldsSql = Object.entries(data).map(([field, value], index) => {
            if (value instanceof Date) {
                values[index] = value.toISOString();
                return `${Sqlite.#quoteIdentifier(field)} = ?`;
            }

            if (value !== null && typeof value === 'object') {
                if (Object.hasOwn(value, 'inc')) {
                    values[index] = value.inc;
                    return `${Sqlite.#quoteIdentifier(field)} = ${Sqlite.#quoteIdentifier(field)} + ?`;
                }
                if (Object.hasOwn(value, 'dec')) {
                    values[index] = value.dec;
                    return `${Sqlite.#quoteIdentifier(field)} = ${Sqlite.#quoteIdentifier(field)} - ?`;
                }
                if (typeof value.toSqlString === 'function') {
                    values[index] = Sqlite.#rawSqlSentinel;
                    return `${Sqlite.#quoteIdentifier(field)} = ${value.toSqlString()}`;
                }
                return `${Sqlite.#quoteIdentifier(field)} = ?`;
            }

            return `${Sqlite.#quoteIdentifier(field)} = ?`;
        }).join(', ');

        let whereSql = `${Sqlite.#quoteIdentifier('id')} = ?`;
        if (typeof id === 'object') {
            const { statement, values: filterValues } = Sqlite.getWhereStatements(id);
            whereSql = statement;
            values.push(...filterValues);
        } else {
            values.push(id);
        }

        const sql = `UPDATE ${Sqlite.#quoteIdentifier(table)} SET ${fieldsSql} WHERE ${whereSql} RETURNING *`;
        return Sqlite.#query(sql, values.filter(value => value !== Sqlite.#rawSqlSentinel), context);
    }

    /**
     * Deletes rows by id or by a filter object.
     *
     * @param {string} table
     * @param {number|string|Record<string, unknown>} clause
     * @param {{ limit?: number }} [opt]
     * @param {{ connection?: DatabaseSync }} [context]
     * @returns {unknown[]}
     */
    static delete(table, clause, opt = {}, context = {}) {
        if (clause === undefined || clause === null) {
            throw new DatabaseError(400, 'Invalid clause for delete operation.');
        }

        const values = [];
        let whereSql = `${Sqlite.#quoteIdentifier('id')} = ?`;
        if (typeof clause === 'object') {
            const where = Sqlite.getWhereStatements(clause);
            whereSql = where.statement;
            values.push(...where.values);
        } else {
            values.push(clause);
        }

        let sql;
        if (opt.limit) {
            const limit = parseInt(opt.limit, 10);
            sql = `DELETE FROM ${Sqlite.#quoteIdentifier(table)} WHERE ${Sqlite.#quoteIdentifier('id')} IN (SELECT ${Sqlite.#quoteIdentifier('id')} FROM ${Sqlite.#quoteIdentifier(table)} WHERE ${whereSql} LIMIT ${limit})`;
        } else {
            sql = `DELETE FROM ${Sqlite.#quoteIdentifier(table)} WHERE ${whereSql}`;
        }

        return Sqlite.#query(sql, values, context);
    }

    /**
     * Finds rows using filter, projection, ordering, and paging options.
     *
     * @param {string} table
     * @param {{ filter?: Record<string, unknown>, view?: string|string[], opt?: Record<string, unknown> }} [options]
     * @param {{ connection?: DatabaseSync }} [context]
     * @returns {unknown[]}
     */
    static find(table, { filter = {}, view = [], opt = {} } = {}, context = {}) {
        if (typeof filter !== 'object' || Array.isArray(filter)) {
            throw new DatabaseError(400, 'Invalid filter for find operation.');
        }

        view = Array.isArray(view) ? view : [view];
        const viewSql = view.length ? view.map(field => Sqlite.#quoteIdentifier(field)).join(',') : '*';

        const { statement, values } = Sqlite.getWhereStatements(filter);
        const whereSql = Object.keys(filter).length ? ` WHERE ${statement}` : '';
        const orderSql = opt.order && Object.keys(opt.order).length
            ? ` ORDER BY ${Object.entries(opt.order).map(([field, direction]) => `${Sqlite.#quoteIdentifier(field)} ${direction === 1 || direction === 'ASC' || direction === 'asc' ? 'ASC' : 'DESC'}`).join(', ')}`
            : '';
        const limitSql = opt.limit ? ` LIMIT ${parseInt(opt.limit, 10)}` : '';
        const offsetSql = opt.skip ? ` OFFSET ${parseInt(opt.skip, 10)}` : '';

        const sql = `SELECT ${viewSql} FROM ${Sqlite.#quoteIdentifier(table)}${whereSql}${orderSql}${limitSql}${offsetSql}`;
        return Sqlite.#query(sql, values, context);
    }

    /**
     * Finds one row or returns null when no row matches.
     *
     * @param {string} table
     * @param {{ filter?: Record<string, unknown>, view?: string|string[], opt?: Record<string, unknown> }} [options]
     * @param {{ connection?: DatabaseSync }} [context]
     * @returns {Record<string, unknown>|null}
     */
    static findOne(table, options = {}, context = {}) {
        const rows = Sqlite.find(table, {
            ...options,
            opt: { ...(options.opt || {}), limit: 1 },
        }, context);
        return rows[0] || null;
    }

    /**
     * Gets a single row by id or throws when it is missing.
     *
     * @param {string} table
     * @param {number|string} id
     * @param {{ connection?: DatabaseSync }} [context]
     * @returns {Record<string, unknown>}
     */
    static get(table, id, context = {}) {
        const row = Sqlite.findOne(table, { filter: { id } }, context);
        if (!row) {
            throw new DatabaseError(404, 'Record not found.', 'RECORD_NOT_FOUND');
        }
        return row;
    }

    /**
     * Builds SQL WHERE snippets and values from a filter object.
     *
     * @param {Record<string, unknown>} filter
     * @returns {{ statement: string, values: unknown[] }}
     */
    static getWhereStatements(filter) {
        const values = [];

        const statement = Object.entries(filter).map(([field, value]) => {
            const quotedField = Sqlite.#quoteIdentifier(field);

            if (value === null) {
                return `${quotedField} IS NULL`;
            }

            if (Array.isArray(value)) {
                if (!value.length) return '1=0';
                values.push(...value);
                return `${quotedField} IN (${value.map(() => '?').join(',')})`;
            }

            if (typeof value === 'object') {
                if (Object.hasOwn(value, 'in')) {
                    if (!Array.isArray(value.in) || !value.in.length) return '1=0';
                    values.push(...value.in);
                    return `${quotedField} IN (${value.in.map(() => '?').join(',')})`;
                }
                if (Object.hasOwn(value, 'between')) {
                    values.push(value.between[0], value.between[1]);
                    return `${quotedField} BETWEEN ? AND ?`;
                }
                if (Object.hasOwn(value, 'like')) {
                    values.push(`%${value.like}%`);
                    return `${quotedField} LIKE ?`;
                }
                if (Object.hasOwn(value, 'not')) {
                    if (value.not === null) {
                        return `${quotedField} IS NOT NULL`;
                    }
                    values.push(value.not);
                    return `${quotedField} != ?`;
                }

                const operator = Object.keys(value)[0];
                if (!['<', '<=', '>', '>=', '!='].includes(operator)) {
                    throw new DatabaseError(400, 'Invalid filter operation.');
                }
                values.push(value[operator]);
                return `${quotedField} ${operator} ?`;
            }

            values.push(value);
            return `${quotedField} = ?`;
        }).join(' AND ');

        return { statement, values };
    }

    /**
     * Runs an operation inside an atomic SQLite transaction.
     *
     * @template T
     * @param {(context: { connection: DatabaseSync }) => T} operation
     * @returns {T}
     */
    static withTransaction(operation) {
        if (!Sqlite.connected) {
            Sqlite.connect();
        }
        const db = Sqlite.connection;
        db.exec('BEGIN TRANSACTION;');
        try {
            const result = operation({ connection: db });
            db.exec('COMMIT;');
            return result;
        } catch (error) {
            try {
                db.exec('ROLLBACK;');
            } catch {}
            throw error;
        }
    }

    /**
     * Wraps trusted SQL so it can be embedded in generated statements.
     *
     * @param {string} sql
     * @returns {{ toSqlString: () => string }}
     */
    static raw(sql) {
        return { toSqlString: () => sql };
    }

    /**
     * Removes raw SQL fragments from the placeholder data before execution.
     *
     * @param {string} sql
     * @param {unknown[]} [data]
     * @returns {{ sql: string, data: unknown[] }}
     */
    static formatRaw(sql, data = []) {
        const originalSql = sql;
        const pieces = sql.split('?');

        if (pieces.length > 1) {
            let joinedSql = pieces.shift();

            try {
                data.forEach(value => {
                    joinedSql += value && typeof value.toSqlString === 'function'
                        ? value.toSqlString()
                        : '?';
                    joinedSql += pieces.shift();
                });
                sql = joinedSql;
            } catch {
                sql = originalSql;
            }

            data = Array.isArray(data)
                ? data.filter(value => !value || typeof value.toSqlString !== 'function')
                : data;
        }

        return { sql, data };
    }

    /**
     * Formats SQL statement with values for debugging.
     *
     * @param {string} sql
     * @param {unknown[]} [data]
     * @returns {string}
     */
    static format(sql, data = []) {
        let formatted = sql;
        data.forEach((val) => {
            const strVal = typeof val === 'string' ? `'${val.replace(/'/g, "''")}'` : String(val);
            formatted = formatted.replace('?', strVal);
        });
        return formatted;
    }

    /**
     * Converts a timestamp-like value into ISO format for SQLite.
     *
     * @param {string|number|Date} timestamp
     * @returns {string}
     */
    static toDateTime(timestamp) {
        return new Date(timestamp).toISOString();
    }

    static like(str) {
        return { like: str };
    }

    static between(a, b) {
        return { between: [a, b] };
    }

    static ne(value) {
        return { not: value };
    }

    static lt(value) {
        return { '<': value };
    }

    static gt(value) {
        return { '>': value };
    }

    static lte(value) {
        return { '<=': value };
    }

    static gte(value) {
        return { '>=': value };
    }
}
